# Generated by Django 3.2 on 2022-09-25 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='title',
            new_name='name',
        ),
    ]
