# Generated by Django 3.2 on 2022-09-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20220925_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='statute',
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(blank=True, choices=[('OP', 'opened'), ('CL', 'closed')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='name',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
