# Generated by Django 3.2 on 2022-09-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20220925_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', 'LOW'), ('meduim', 'MEDUIM'), ('high', 'HIGH')], max_length=8, null=True),
        ),
    ]
