# Generated by Django 3.2 on 2022-10-03 09:53

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_priority'),
    ]

    # operations = [
    #     migrations.AddConstraint(
    #         model_name='event',
    #         constraint=models.CheckConstraint(check=models.Q(deadline__gt=django.db.models.expressions.F('start_date')), name='date_check'),
    #     ),
    # ]
