# Generated by Django 3.2 on 2022-11-27 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(blank=True, decimal_places=0, max_digits=100000, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=0, max_digits=100000, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('to_name', models.CharField(blank=True, max_length=450, null=True)),
                ('to_postal_code', models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True)),
                ('to_phone', models.CharField(blank=True, max_length=13, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('bill_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='Invoice', serialize=False, to='bills.bill')),
                ('number', models.IntegerField(blank=True, default=0, null=True, verbose_name='Numéro de facture')),
            ],
            options={
                'default_related_name': 'Invoice',
            },
            bases=('bills.bill',),
        ),
        migrations.CreateModel(
            name='Proforma',
            fields=[
                ('bill_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='Proforma', serialize=False, to='bills.bill')),
                ('number', models.IntegerField(blank=True, default=0, null=True, verbose_name='Numéro de Proforma')),
            ],
            options={
                'default_related_name': 'Proforma',
            },
            bases=('bills.bill',),
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=180, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('tax', models.BooleanField(default=False)),
                ('tva', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('term', models.TextField(blank=True, null=True)),
                ('bill_ofc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bills.bill')),
            ],
        ),
    ]
