# Generated by Django 3.2 on 2022-09-04 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cashflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=180, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('tax', models.BooleanField(default=False)),
                ('tva', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('term', models.TextField(blank=True, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=100000)),
                ('discount', models.DecimalField(decimal_places=0, max_digits=100000)),
                ('postal_code', models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True)),
                ('to_name', models.CharField(blank=True, max_length=180, null=True)),
                ('to_postal_code', models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True)),
                ('to_phone', models.CharField(blank=True, max_length=13, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashflow.account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=180, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('tax', models.BooleanField(default=False)),
                ('tva', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('term', models.TextField(blank=True, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=100000)),
                ('discount', models.DecimalField(decimal_places=0, max_digits=100000)),
                ('postal_code', models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True)),
                ('to_name', models.CharField(blank=True, max_length=180, null=True)),
                ('to_postal_code', models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True)),
                ('to_phone', models.CharField(blank=True, max_length=13, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashflow.account')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
