# Generated by Django 3.2 on 2022-09-06 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0001_initial'),
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='price',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='proforma',
            old_name='price',
            new_name='cost',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='account',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='description',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='note',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='number',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='term',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='to_name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='to_phone',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='to_postal_code',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tva',
        ),
        migrations.RemoveField(
            model_name='proforma',
            name='account',
        ),
        migrations.RemoveField(
            model_name='proforma',
            name='description',
        ),
        migrations.RemoveField(
            model_name='proforma',
            name='name',
        ),
        migrations.RemoveField(
            model_name='proforma',
            name='note',
        ),
        migrations.RemoveField(
            model_name='proforma',
            name='number',
        ),
        migrations.RemoveField(
            model_name='proforma',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='proforma',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='proforma',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='proforma',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='proforma',
            name='term',
        ),
        migrations.RemoveField(
            model_name='proforma',
            name='to_name',
        ),
        migrations.RemoveField(
            model_name='proforma',
            name='to_phone',
        ),
        migrations.RemoveField(
            model_name='proforma',
            name='to_postal_code',
        ),
        migrations.RemoveField(
            model_name='proforma',
            name='tva',
        ),
        migrations.AddField(
            model_name='invoice',
            name='account1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_account', to='cashflow.account'),
        ),
        migrations.AddField(
            model_name='proforma',
            name='account2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proforma_account', to='cashflow.account'),
        ),
    ]
