# Generated by Django 3.2 on 2022-11-27 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bills', '0001_initial'),
        ('cashflow', '0001_initial'),
        ('contact', '0002_company_postal_code_alter_company_company_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_account', to='cashflow.account'),
        ),
        migrations.AddField(
            model_name='bill',
            name='from_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bills_sent', to='contact.company'),
        ),
        migrations.AddField(
            model_name='bill',
            name='to_companty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bills_received', to='contact.company'),
        ),
    ]
