# Generated by Django 3.2 on 2022-09-06 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_company_postal_code'),
        ('cashflow', '0001_initial'),
        ('bills', '0002_auto_20220906_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=0, max_digits=100000)),
                ('discount', models.DecimalField(decimal_places=0, max_digits=100000)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_account', to='cashflow.account')),
                ('from_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills_sent', to='contact.company')),
                ('to_companty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills_received', to='contact.company')),
            ],
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'default_related_name': 'Invoice'},
        ),
        migrations.AlterModelOptions(
            name='proforma',
            options={'default_related_name': 'Proforma'},
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='account1',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='created',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='id',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='proforma',
            name='account2',
        ),
        migrations.RemoveField(
            model_name='proforma',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='proforma',
            name='created',
        ),
        migrations.RemoveField(
            model_name='proforma',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='proforma',
            name='id',
        ),
        migrations.RemoveField(
            model_name='proforma',
            name='updated',
        ),
        migrations.AddField(
            model_name='invoice',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Numéro de facture'),
        ),
        migrations.AddField(
            model_name='proforma',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Numéro de Proforma'),
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=180, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('tax', models.BooleanField(default=False)),
                ('tva', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('term', models.TextField(blank=True, null=True)),
                ('bill_ofc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bills.bill')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='bill_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='Invoice', serialize=False, to='bills.bill'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proforma',
            name='bill_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='Proforma', serialize=False, to='bills.bill'),
            preserve_default=False,
        ),
    ]
