# Generated by Django 4.1.3 on 2022-11-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bills", "0003_alter_invoice_bill_ptr_alter_proforma_bill_ptr"),
    ]

    operations = [
        migrations.AddField(
            model_name="billitem",
            name="total_price_item",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
