# Generated by Django 4.1.3 on 2022-11-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bills", "0004_billitem_total_price_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="billitem",
            name="total_price",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="billitem",
            name="total_price_hors_taxe",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
