# Generated by Django 3.2 on 2022-09-07 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_auto_20220906_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_bill',
        ),
        migrations.RemoveField(
            model_name='proforma',
            name='proforma_bill',
        ),
        migrations.AddField(
            model_name='invoice',
            name='bill_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='Invoice', serialize=False, to='bills.bill'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proforma',
            name='bill_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='Proforma', serialize=False, to='bills.bill'),
            preserve_default=False,
        ),
    ]
