# Generated by Django 3.2 on 2022-09-24 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_company_postal_code'),
        ('cashflow', '0001_initial'),
        ('bills', '0005_auto_20220907_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='to_phone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='to_postal_code',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_account', to='cashflow.account'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=100000, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=100000, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='from_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bills_sent', to='contact.company'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='to_companty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bills_received', to='contact.company'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Numéro de facture'),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='number',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Numéro de Proforma'),
        ),
    ]
