# Generated by Django 4.1.3 on 2022-11-30 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bills", "0005_billitem_total_price_billitem_total_price_hors_taxe"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="billitem",
            name="total_price",
        ),
        migrations.RemoveField(
            model_name="billitem",
            name="total_price_hors_taxe",
        ),
        migrations.RemoveField(
            model_name="billitem",
            name="total_price_item",
        ),
    ]
