# Generated by Django 3.2 on 2022-09-24 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0006_auto_20220924_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='due_date',
            field=models.DateField(auto_now=True),
        ),
    ]
