# Generated by Django 3.2 on 2022-09-24 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0007_bill_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
