# Generated by Django 3.2 on 2022-09-24 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0008_alter_bill_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='to_name',
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
    ]
