# Generated by Django 4.1.3 on 2022-11-21 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bills", "0009_auto_20220924_0231"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="bill_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="bills.bill",
            ),
        ),
        migrations.AlterField(
            model_name="proforma",
            name="bill_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="bills.bill",
            ),
        ),
    ]
