# Generated by Django 3.2 on 2022-09-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='postal_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
