# Generated by Django 4.1.3 on 2022-11-26 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="postal_code",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="The postal Code"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="company_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CLIENT", "client"),
                    ("FOURNISSEUR", "fournisseur"),
                    ("PARTENAIRE", "partenaire"),
                    ("CONCURRENT", "concurrent"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="project_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("E-COMMERCE", "e-commerce"),
                    ("WEB SITE", "web site"),
                    ("WEB APP", "web app"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="responsible_person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="companies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsable de la société",
            ),
        ),
    ]
