# Generated by Django 3.2 on 2022-11-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_company_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_type',
            field=models.CharField(blank=True, choices=[('CLIENT', 'client'), ('FOURNISSEUR', 'fournisseur'), ('PARTENAIRE', 'partenaire'), ('CONCURRENT', 'concurrent')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='project_type',
            field=models.CharField(blank=True, choices=[('E-COMMERCE', 'e-commerce'), ('WEB SITE', 'web site'), ('WEB APP', 'web app')], max_length=20, null=True),
        ),
    ]
