# Generated by Django 3.2 on 2022-11-27 14:27

import accounts.models
from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/faces')),
                ('pseudo', models.CharField(blank=True, max_length=150, null=True)),
                ('role', models.CharField(blank=True, choices=[('DESGFNER', 'designer'), ('DEVELOPER', 'developer'), ('ASSISTANT', 'assistant'), ('COMMERCIAL', 'commercial'), ('MARKETER', 'marketer'), ('CONTENT CREATOR', 'content creator')], max_length=20, null=True)),
                ('decision', models.CharField(blank=True, choices=[('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], max_length=2, null=True)),
                ('mobile', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('notes', tinymce.models.HTMLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_manager', models.BooleanField(default=False)),
                ('is_responsible', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_internal', models.BooleanField(default=False)),
                ('user_type', models.CharField(blank=True, choices=[('INTERNE', 'interne'), ('EXTERNE', 'externe')], max_length=20, null=True)),
                ('project_name', models.CharField(blank=True, max_length=120, null=True)),
                ('collab_start', models.DateField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=250, null=True)),
                ('created', models.DateField(auto_now=True)),
                ('updated', models.DateField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
    ]
