# Generated by Django 3.2 on 2022-11-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='client_lead',
            field=models.CharField(blank=True, choices=[('INTERESTED', 'interested'), ('CALL AGAIN', 'call again'), ('NOT INTERESTED', 'not interested')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='project_type',
            field=models.CharField(blank=True, choices=[('E-COMMERCE', 'e-commerce'), ('WEB SITE', 'web site'), ('WA', 'web app')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('DESGFNER', 'designer'), ('DEVELOPER', 'developer'), ('ASSISTANT', 'assistant'), ('COMMERCIAL', 'commercial'), ('MARKETER', 'marketer'), ('CONTENT CREATOR', 'content creator')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('INTERNE', 'interne'), ('EXTERNE', 'externe')], max_length=20, null=True),
        ),
    ]
