# Generated by Django 3.2 on 2022-11-19 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20221109_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='client_lead',
        ),
        migrations.RemoveField(
            model_name='user',
            name='project_type',
        ),
    ]
