# Generated by Django 3.2 on 2022-09-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220906_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fonction',
        ),
        migrations.AlterField(
            model_name='user',
            name='client_lead',
            field=models.CharField(choices=[('I', 'interested'), ('CA', 'call again'), ('NI', 'not intrested')], max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('DS', 'design'), ('DV', 'developer'), ('AS', 'Assistant'), ('CM', 'Commercial'), ('MK', 'Marketer'), ('CC', 'Content creater')], max_length=2, null=True),
        ),
    ]
