# Generated by Django 3.2 on 2022-09-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220907_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='client_lead',
            field=models.CharField(choices=[('I', 'inrested'), ('CA', 'call again'), ('NI', 'not intrested')], max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('DS', 'designer'), ('WD', 'developer'), ('CM', 'commercial'), ('MK', 'marketer'), ('CC', 'content creator'), ('AS', 'assistant')], max_length=2, null=True),
        ),
    ]
