# Generated by Django 3.2 on 2022-09-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220911_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('DS', 'designer'), ('DV', 'developer'), ('AS', 'assistant'), ('CM', 'commercial'), ('MK', 'marketer'), ('CC', 'content creator')], max_length=2, null=True),
        ),
    ]
