# Generated by Django 3.2 on 2022-09-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='client_lead',
            field=models.CharField(blank=True, choices=[('I', 'inrested'), ('CA', 'call again'), ('NI', 'not intrested')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
