# Generated by Django 3.2 on 2022-09-21 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_company_postal_code'),
        ('accounts', '0007_user_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_company', to='contact.company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('IN', 'interne'), ('EX', 'externe')], max_length=2, null=True),
        ),
    ]
