# Generated by Django 3.2 on 2022-09-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20220921_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_responsible',
            field=models.BooleanField(default=False),
        ),
    ]
