# Generated by Django 3.2 on 2022-11-27 14:22

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=252, null=True)),
                ('acc_type', models.CharField(blank=True, choices=[('IN', 'In'), ('OUT', 'Out')], db_index=True, max_length=3, null=True)),
                ('actif', models.BooleanField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=180, null=True)),
                ('tr_type', models.CharField(blank=True, choices=[('PA', 'paiement'), ('SA', 'salaire '), ('CR', 'creance'), ('CH', 'charges'), ('AL', 'allouer')], max_length=2, null=True)),
                ('tr_status', models.CharField(blank=True, choices=[('PAID', 'paid'), ('NOT_PAID', 'not paid'), ('PENDING', 'pending')], max_length=13, null=True)),
                ('other', models.CharField(blank=True, max_length=254, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=254, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('account_rc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='cashflow.account')),
                ('account_sd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='cashflow.account')),
                ('made_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='made_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
