# Generated by Django 3.2 on 2022-09-24 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0002_alter_account_acc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='name',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tr_status',
            field=models.CharField(blank=True, choices=[('payed', 'PAYED'), ('not payed', 'NOT_PAYED'), ('pending', 'PENDING')], max_length=13, null=True),
        ),
    ]
