# Generated by Django 3.2 on 2022-11-27 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='account_sd',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='cashflow.account'),
            preserve_default=False,
        ),
    ]
