# Generated by Django 4.1.3 on 2022-11-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cashflow", "0003_remove_account_postal_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="acc_type",
            field=models.CharField(
                blank=True,
                choices=[("IN", "In"), ("OUT", "Out")],
                db_index=True,
                max_length=3,
                null=True,
            ),
        ),
    ]
