# Generated by Django 3.2 on 2022-09-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0003_auto_20220925_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tr_status',
            field=models.CharField(blank=True, choices=[('PAID', 'paid'), ('NOT_PAID', 'not paid'), ('PENDING', 'pending')], max_length=13, null=True),
        ),
    ]
