# Generated by Django 3.2 on 2022-09-25 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20220922_1051'),
        ('cashflow', '0004_alter_transaction_tr_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='actif',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
    ]
