# Generated by Django 3.2 on 2022-09-25 13:35

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0006_alter_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=100000, max_digits=120000, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))]),
        ),
    ]
