# Generated by Django 3.2 on 2022-09-04 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('cost', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('started_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('project_type', models.CharField(blank=True, choices=[('EC', 'e-commerce'), ('WS', 'web site'), ('WA', 'web app')], max_length=2, null=True)),
                ('contract', models.CharField(blank=True, choices=[('H', 'hosting'), ('A', 'annual'), ('S', 'semi-annual'), ('Q', 'quarterly'), ('AD', 'adverisement')], max_length=2, null=True)),
                ('contract_expiration', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('CF', 'Confirm'), ('CP', 'Completed'), ('PE', 'Pending'), ('CA', 'Cancelled')], max_length=2, null=True)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='contact.company', verbose_name='client')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_managers', to=settings.AUTH_USER_MODEL, verbose_name='manager')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_teams', to=settings.AUTH_USER_MODEL, verbose_name='team')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='project.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervised_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
