# Generated by Django 3.2 on 2022-09-25 13:52

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20220922_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
