# Generated by Django 3.2 on 2022-10-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_project_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='started_date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', 'LOW'), ('meduim', 'MEDUIM'), ('high', 'HIGH')], max_length=7, null=True),
        ),
    ]
