# Generated by Django 3.2 on 2022-10-20 09:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0004_auto_20221012_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='team',
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ManyToManyField(blank=True, null=True, related_name='project_teams', to=settings.AUTH_USER_MODEL, verbose_name='team'),
        ),
    ]
