# Generated by Django 3.2 on 2022-10-31 15:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0013_auto_20221031_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ManyToManyField(related_name='project_teams', through='project.Teams', to=settings.AUTH_USER_MODEL, verbose_name='team'),
        ),
    ]
