# Generated by Django 3.2 on 2022-11-09 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0013_auto_20221031_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='is_responsible',
        ),
        migrations.AlterField(
            model_name='project',
            name='contract',
            field=models.CharField(blank=True, choices=[('HOSTING', 'hosting'), ('ANNUAL', 'annual'), ('SEMI-ANNUAL', 'semi-annual'), ('QUARTERLY', 'quarterly'), ('ADVERTISEMENT', 'advertisement')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(blank=True, choices=[('E-COMMERCE', 'e-commerce'), ('WEB SITE', 'web site'), ('WEB APP', 'web app')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', 'LOW'), ('meduim', 'MEDUIM'), ('high', 'HIGH')], max_length=20, null=True),
        ),
        migrations.RemoveField(
            model_name='teams',
            name='member',
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_responsible', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_member_of_team', to=settings.AUTH_USER_MODEL, verbose_name='member_of_team')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_member_of_project', to='project.teams', verbose_name='team_of_project')),
            ],
        ),
        migrations.AddField(
            model_name='teams',
            name='member',
            field=models.ManyToManyField(through='project.TeamMember', to=settings.AUTH_USER_MODEL, verbose_name='member'),
        ),
    ]
