# Generated by Django 3.2 on 2022-11-02 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_project_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='team',
        ),
    ]
