# Generated by Django 3.2 on 2022-11-02 15:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0015_remove_project_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='member',
        ),
        migrations.AddField(
            model_name='teams',
            name='member',
            field=models.ManyToManyField(related_name='team_member', to=settings.AUTH_USER_MODEL, verbose_name='member'),
        ),
    ]
