# Generated by Django 3.2 on 2022-11-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_auto_20221102_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contract',
            field=models.CharField(blank=True, choices=[('HOSTING', 'hosting'), ('ANNUAL', 'annual'), ('SEMI-ANNUAL', 'semi-annual'), ('QUARTERLY', 'quarterly'), ('ADVERTISEMENT', 'advertisement')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(blank=True, choices=[('E-COMMERCE', 'e-commerce'), ('WEB SITE', 'web site'), ('WEB APP', 'web app')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', 'LOW'), ('meduim', 'MEDUIM'), ('high', 'HIGH')], max_length=20, null=True),
        ),
    ]
